name: uol_edtech_challenge
description: Test Challenge. List of classes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  get: 4.5.1
  flutter_dotenv: 5.0.2
  easy_localization: 3.0.0
  date_format: 2.0.4
  flutter_launcher_icons: 0.9.2
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/langs/
    - fake_classes.json

flutter_icons:
  image_path: assets/images/512x512_android.png
  android: true
  ios: true
  image_path_android: assets/images/512x512_android.png
  image_path_ios: assets/images/512x512_ios.jpg
  adaptive_icon_foreground: assets/images/logo_android_Adaptive.png
  adaptive_icon_background: assets/images/White_background.png